package mert.kadakal.yazlmblog.ui.blog;// File: CommonList.java
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class EtiketlerList {
    public static final ArrayList<String> LIST = new ArrayList<>(List.of(
            "Yazılım Dilleri",
            "Oyun Geliştirme",
            "Web Geliştirme",
            "Eğitim",
            "Java",
            "Python",
            "C++",
            "C#",
            "JavaScript",
            "Kotlin",
            "Swift",
            "Go",
            "Rust",
            "PHP",
            "Ruby",
            "TypeScript",
            "Dart",
            "R",
            "Scala",
            "Perl",
            "HTML & CSS",
            "Veri Yapıları",
            "Algoritmalar",
            "Yapay Zeka",
            "Makine Öğrenmesi",
            "Derin Öğrenme",
            "Veri Bilimi",
            "Siber Güvenlik",
            "Blockchain",
            "Mobil Geliştirme",
            "Backend Geliştirme",
            "Frontend Geliştirme",
            "Fullstack Geliştirme",
            "Bulut Bilişim",
            "DevOps",
            "Veritabanları",
            "SQL",
            "NoSQL",
            "API Geliştirme",
            "Mikroservisler",
            "Agile & Scrum",
            "Yazılım Testi",
            "Unit Test",
            "Clean Code",
            "Design Patterns",
            "OOP",
            "Functional Programming",
            "Versiyon Kontrol (Git)",
            "Linux & Sistem Programlama"
    ));
}
